### PR TITLE
added --help and basic setup for open source work

### PR DESCRIPTION
**Pull request by kaerns**
- refactored the code for better readability and parameter extensions
- added --help option for some basic usage
- added CONTRIBUTING.md for better collaboration with open source contributers
- added LICENSE to clarify what people are allowed and what not
- renamed the script, tutorial on TeaSpeak will be updated on merge

### CODE REVIEW

**Comment by kaerns** [comment]
@Coolguy3289 It'd be nice from you to review the changes since I changed some of your changes.

**Review by Coolguy3289 — CHANGES_REQUESTED** [review]
I wouldn't use GPLv3 tbh, it's a bash script that just downloads and copies files. I'd recommend the MIT license instead.

**Comment by kaerns** [comment]
Is there any real difference between both except for some more redistribution-conditions? Or can you explain why MIT is better suited?

**Comment by Coolguy3289** [comment]
For the type of script this is, having GPL just over-complicates it in my opinion. MIT is just a simple license for a simple script

**Comment by kaerns** [comment]
I've read the MIT license and even though it's short and easy to understand I decided to stay with GLPv3 for now.
I just like it for the additional conditions it provides.

**Pull request merged**
